### ISSUE TITLE
Adding the deploy command in the README

### ISSUE THREAD

**Issue by wongJonathan** [Jimdo/serverless-dynamodb-ttl#9]
Hi, it might be my inexperience using serverless but I think it may be useful to add an example serverless deploy command. I was running into a `No Region` error because I didn't realize  that I needed to set the region as an option until I looked through the code. Otherwise it great job!

**Comment by sbstjn** [comment]
Thanks for the input! I'll have a look how we can enhance this.

**Comment by sbstjn** [comment]
We updated the configuration handling for `region` and `provider` and with `0.0.7` you should not need to configure the region. The plugin will use the serverless default region.

**Comment by wongJonathan** [comment]
Okay thank you very much!

**Comment by sbstjn** [comment]
You're welcome. Please let us know if the handling is still not optimal.
